version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      # 1.6.9, 1.6.10 and 1.6.11 are broken; see NEXUS-31214.
      - dependency-name: "org.sonatype.plugins:nexus-staging-maven-plugin"
        versions: ["1.6.9", "1.6.10", "1.6.11"]
