version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      # 3.2.8 is broken.
      - dependency-name: "org.apache.maven.plugins:maven-gpg-plugin"
        versions: ["3.2.8"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "daily"
